/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-tint": "#0c56d0",
        "primary-container": "#0052cc",
        "secondary": "#285ab9",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#00419d",
        "on-surface-variant": "#434654",
        "on-primary-container": "#c4d2ff",
        "tertiary-fixed-dim": "#a7c8ff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#b1c6ff",
        "surface-container": "#edeef0",
        "on-secondary-fixed": "#001946",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#709bfe",
        "on-error-container": "#93000a",
        "surface-variant": "#e1e2e4",
        "surface": "#f8f9fb",
        "outline-variant": "#c3c6d6",
        "outline": "#737685",
        "surface-container-low": "#f3f4f6",
        "on-tertiary-fixed": "#001b3c",
        "primary-fixed": "#dae2ff",
        "on-primary": "#ffffff",
        "on-background": "#191c1e",
        "tertiary": "#004483",
        "tertiary-container": "#005bac",
        "surface-container-high": "#e7e8ea",
        "primary-fixed-dim": "#b2c5ff",
        "on-surface": "#191c1e",
        "surface-bright": "#f8f9fb",
        "inverse-surface": "#2e3132",
        "on-tertiary-container": "#bdd4ff",
        "error-container": "#ffdad6",
        "background": "#f8f9fb",
        "inverse-primary": "#b2c5ff",
        "inverse-on-surface": "#f0f1f3",
        "secondary-fixed": "#d9e2ff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#001848",
        "on-secondary-container": "#003179",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#d5e3ff",
        "surface-container-highest": "#e1e2e4",
        "primary": "#003d9b",
        "on-tertiary-fixed-variant": "#004788",
        "surface-dim": "#d9dadc",
        "on-primary-fixed-variant": "#0040a2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xxl": "48px",
        "container-max": "1440px",
        "base": "4px",
        "lg": "24px",
        "md": "16px",
        "xs": "4px",
        "xl": "32px",
        "sm": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "code-sm": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "60px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "code-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
